<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 */

/**
 * Implementation of hook_init().
 */
function acquiasdk_init() {
  acquiasdk_classloader();
}

/**
 * Loads the class loader in order to register all Acquia SDK PHP namespaces.
 */
function acquiasdk_classloader() {
  static $loader = NULL;
  
  // Load Composer's autoloader to expose Acquia SDK PHP.
  if (!isset($loader)) {
    // The vendor can either be in modules/acquiasdk/vendor, or sites/all/vendor.
    foreach (array(__DIR__, dirname(dirname(__DIR__))) as $path) {
      $loader = @include_once $path . '/vendor/autoload.php';
      if ($loader) {
        return $loader;
      }
    }

    // Display a warning about the autoloader not being able to load.
    if (!$loader) {
      $message = t('You must install Acquia SDK PHP by running a Composer install from the %path directory.', array(
        '%path' => __DIR__,
      ));
      drupal_set_message($message, 'warning', FALSE);
    }
  }

  return $loader;
}

